vunit: Isolate single test run to avoid release mode clobbered warning
When compiling in release mode with gcc the folowing error appears:

../subprojects/vunit/vunit.c: In function ‘__vunit_main’:
../subprojects/vunit/vunit.c:96:16: error: variable ‘num’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
   96 |         size_t num = 0;
      |                ^~~

This happening because the compiler inlines the function
get_num_tests() called in function the uses setjmp (__vunit_main()).

To fix that, isolate the procedure inside the loop that runs a single
test and has the setjmp.